### ISSUE TITLE
Getting a version with number "5.7.4.efdJ1W" instead of "5.7.4" after update

### ISSUE THREAD

**Issue by MahatmaBandi** [AoE2CommunityGitHub/WololoKingdoms#11]
After updating my mod from 5.7.2 to latest version, it stopped working properly. Hosting or joining a game is impossible because the version numbers don't match up, that's even so when I am the host, and the only player in the room (see next image).
![err2](https://user-images.githubusercontent.com/30826103/45219506-69dc5800-b2ab-11e8-94af-f9831eedc0fd.PNG)
I tried reinstalling WololoKingdoms multiple times, also by deleting all files in the Data Mods folder. I have also run Game Diagnostics which could not find the problem either.

The only workaround I found is to edit the version.ini file manually to "5.7.4" (see next picture). Unfortunately that made the game unstable, making almost all of my 1v1 games played with it out of sync at some point.
![version](https://user-images.githubusercontent.com/30826103/45220177-972a0580-b2ad-11e8-9196-133551907ce0.PNG)

I'd like to mention that I got a warning during installation, stating, that I'm not on the correct patch on Steam. That's not true as far as I am aware.
![err1](https://user-images.githubusercontent.com/30826103/45220266-e2441880-b2ad-11e8-8715-57de1f2514a9.PNG)

I am using Windows 10, and have all expansions bought on Steam. I used the following settings during installation:
![sett1](https://user-images.githubusercontent.com/30826103/45220317-07d12200-b2ae-11e8-98b0-70435f247988.PNG)

What should I do differently? Thanks in advance for your help!

**Comment by gregstein** [comment]
Simply open your version.txt file located at "Voobly Mods\AOC\Data Mods\WololoKingdoms\version.txt" and remove ".efdJ1W" at the end so it looks like "5.7.4" instead of "5.7.4.efdJ1W". Now restart Voobly and everything should be fine now. 

The updater seemed to have mistakenly added ".efdJ1W" at the end, and Jineapple has actually warned about the updater not being at its best shape. But not to worry about it as we have made a a brand new UI Updater that should be replace the current one in the next release of WK.

Let us know how that quick work around worked for you.

**Comment by gregstein** [comment]
In that case, It looks like the updater failed to extract the latest files of wk. I recommend that you delete the directory "Voobly Mods\AOC\Data Mods\WololoKingdoms\" and download/install WK 5.7.4 from stratch from this link: https://github.com/AoE2CommunityGitHub/WololoKingdoms/releases/tag/5.7.4

**Comment by AoE2CommunityGitHub** [comment]
This error happens currently because HD updated to version 5.8, and WololoKingdoms has not been updated yet. Unfortunately the HD team did not communicate ahead of time the date this update was going live, and every update to HD breaks backwards compatibility.

Since HD is not backwards compatible with its patch 5.7 anymore, there currently is no way to downgrade and get the correct version of WK. This is causing all sorts of problems for us, as we need to keep backwards compatibility for currently ongoing tournaments.

There should be an update to WololoKingdoms in the next day or so that resolves these issues. Please try reinstalling then. Alternatively, you can download the current installer and select the option to install the data mod for version 5.7.4. This mod allows you to join games with other people who also are using this data mod (as long as they install it and you select the mod in the Voobly lobby).

**Comment by MahatmaBandi** [comment]
@meichthys I did the same, no results either.
@AoE2CommunityGitHub Ah I see, that explains the error message I got during the installs. I guess we just have to wait then.

**Comment by meichthys** [comment]
@Aoe2CommunityGithub thanks for the explanation. That makes sense.

**Comment by MahatmaBandi** [comment]
With the new update it's all working properly again, so I'll close the issue. Thx for the help!
