### ISSUE TITLE
Wololo patch 5.8

### ISSUE THREAD

**Issue by A1357** [AoE2CommunityGitHub/WololoKingdoms#7]
If i start a Death Match in post Imperial Age some buildings appear to have feudal arhitecture and in the superior UI it says i'm in Feudal Age. Also, will there be an increase in the maximum number of units selected from 40 to 60 like in HD? It feels weird that this mod implements all the changes in HD except this one.

**Comment by Jineapple** [comment]
Do you have a recorded game where this happened? I could potentially see graphics being wrong, but the UI showing Feudal Age despite you being in post imp is rather unlikely.

As for maximum number of units that can be selected - that would be a change for Userpatch, not for WK itself. However, I think this would be very unlikely to happen because this has performance impacts, which Userpatch always tries to avoid.

**Comment by Jineapple** [comment]
Thanks again for the report! I'm glad this could still be caught while in beta. Thanks to scripter, the issue has been found and I'll fix it soon.
